CREATE TABLE users (
    user_id INT PRIMARY KEY,
    first_name VARCHAR(30) NOT NULL,
    last_name VARCHAR(30) NOT NULL,
    email VARCHAR(50) NOT NULL,
    account_created DATETIME DEFAULT CURRENT_TIMESTAMP,
    num_friends INT DEFAULT 0
);
CREATE TABLE posts (
    post_id INT PRIMARY KEY,
    user_id INT,
    post_title TEXT NOT NULL,
    post_body TEXT NOT NULL,
    post_created DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_link
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
);

INSERT INTO users (user_id, first_name, last_name, email, num_friends) VALUES
(1,  'Alice',   'Johnson',  'alice.johnson@example.com',  120),
(2,  'Bob',     'Smith',    'bob.smith@example.com',       45),
(3,  'Carla',   'Martinez', 'carla.martinez@example.com', 210),
(4,  'David',   'Lee',      'david.lee@example.com',        8),
(5,  'Emma',    'Brown',    'emma.brown@example.com',      77),
(6,  'Frank',   'Wilson',   'frank.wilson@example.com',     0),
(7,  'Grace',   'Kim',      'grace.kim@example.com',      153),
(8,  'Henry',   'Davis',    'henry.davis@example.com',     32),
(9,  'Isabel',  'Garcia',   'isabel.garcia@example.com',   91),
(10, 'Jack',    'Thompson', 'jack.thompson@example.com',   14);

INSERT INTO posts (post_id, user_id, post_title, post_body) VALUES
(1,  1,  'Hello World',            'This is my very first post. Excited to be here!'),
(2,  1,  'Weekend Hike',           'Spent the weekend hiking in the Blue Ridge Mountains. The views were incredible.'),
(3,  2,  'Best Pizza in Town',     'I tried a new pizza place downtown and it might be the best I have ever had.'),
(4,  2,  'Book Recommendations',   'Looking for good sci-fi novels. Please send suggestions my way.'),
(5,  3,  'New Job Announcement',   'Thrilled to share that I am starting a new role next month!'),
(6,  3,  'Travel Plans',           'Planning a trip to Portugal this fall. Any tips on where to eat in Lisbon?'),
(7,  3,  'Coffee Addiction',       'Day three of trying to cut back on coffee. Send help.'),
(8,  4,  'Learning Guitar',        'Picked up an acoustic guitar last week. My fingers hurt but I am having fun.'),
(9,  5,  'Garden Update',          'The tomatoes are finally ripening. Homegrown salad tonight!'),
(10, 5,  'Movie Night',            'Hosting a movie night on Friday. Vote for the film in the comments.'),
(11, 6,  'First Post',             'Just joined. Not sure what to say yet, so hi everyone.'),
(12, 7,  'Marathon Training',      'Week six of marathon training complete. Long run of 14 miles done.'),
(13, 7,  'Healthy Recipes',        'Sharing my favorite quinoa bowl recipe. It takes only 20 minutes.'),
(14, 8,  'Fixing Up the Car',      'Spent all Saturday replacing the brakes on my old truck. Satisfying work.'),
(15, 8,  'Football Season',        'Ready for the new season. Who else is excited?'),
(16, 9,  'Art Gallery Visit',      'Visited the new modern art exhibit today. Highly recommend it.'),
(17, 9,  'Rainy Day Reading',      'Nothing beats a rainy afternoon with a good book and hot tea.'),
(18, 9,  'Photography Tips',       'Golden hour really does make everything look better.'),
(19, 10, 'Moving to a New City',   'Packing boxes all week. Moving is exhausting but exciting.'),
(20, 10, 'Podcast Suggestions',    'What podcasts are you listening to lately? I need new ones for my commute.');

-- User names and posts were generated by AI.